# Vector's API for introspection
[api]
enabled = true
address = "127.0.0.1:8686"

# Host-level logs
[sources.logs]
  type = "docker_logs"
  auto_partial_merge = true # optional, default

  # Multiline
  multiline.condition_pattern = '^[\s]+' # required
  multiline.mode = "continue_through" # required
  multiline.start_pattern = '^[^\s]' # required
  multiline.timeout_ms = 1000 # required, milliseconds

[sinks.out]
  # General
  endpoint = "http://loki:3100"
  inputs = ["logs"]
  type = "loki"
  encoding.codec = "json"

  ## Labels
  labels.name = "{{ label.com.docker.swarm.service.name }}"
  labels.stack = "{{ label.com.docker.stack.namespace }}"
  labels.message = "[{{ message }}]"

